#!/bin/bash
python3 main.py bte ~/School/data/ready/a.xml ~/School/data/further-bp/bte/a.xml &
python3 main.py bte ~/School/data/ready/b.xml ~/School/data/further-bp/bte/b.xml &
python3 main.py bte ~/School/data/ready/c.xml ~/School/data/further-bp/bte/c.xml &
python3 main.py bte ~/School/data/ready/d.xml ~/School/data/further-bp/bte/d.xml &
python3 main.py bte ~/School/data/ready/e.xml ~/School/data/further-bp/bte/e.xml &
python3 main.py bte ~/School/data/ready/f.xml ~/School/data/further-bp/bte/f.xml &
python3 main.py bte ~/School/data/ready/g.xml ~/School/data/further-bp/bte/g.xml &
python3 main.py bte ~/School/data/ready/h.xml ~/School/data/further-bp/bte/h.xml &
python3 main.py bte ~/School/data/ready/i.xml ~/School/data/further-bp/bte/i.xml & 
# python3 main.py bte ~/School/data/ready/j.xml ~/School/data/further-bp/bte/j.xml
# python3 main.py bte ~/School/data/ready/k.xml ~/School/data/further-bp/bte/k.xml
# python3 main.py bte ~/School/data/ready/l.xml ~/School/data/further-bp/bte/l.xml
# python3 main.py bte ~/School/data/ready/m.xml ~/School/data/further-bp/bte/m.xml
# python3 main.py bte ~/School/data/ready/n.xml ~/School/data/further-bp/bte/n.xml
# python3 main.py bte ~/School/data/ready/o.xml ~/School/data/further-bp/bte/o.xml
# python3 main.py bte ~/School/data/ready/p.xml ~/School/data/further-bp/bte/p.xml
# python3 main.py bte ~/School/data/ready/q.xml ~/School/data/further-bp/bte/q.xml
# python3 main.py bte ~/School/data/ready/r.xml ~/School/data/further-bp/bte/r.xml
# python3 main.py bte ~/School/data/ready/s.xml ~/School/data/further-bp/bte/s.xml
# python3 main.py bte ~/School/data/ready/t.xml ~/School/data/further-bp/bte/t.xml