from elasticsearch import Elasticsearch
es = Elasticsearch(urls=['localhost'], port=9200)

queries = [
"kazar comic",
"dc digest",
"vintage bronze sculpture",
"roman replica",
"deer sculpture",
"usmc",
"multicam",
"new woodland pants",
"jim shore bunny",
"disney traditions",
"heartwood creek angels",
"mexico carved wood",
"oaxacan",
"milagros",
"wooden radio",
"rare zenith",
"stromberg carlson",
"hexagon box",
"hinged trinket box",
"blue glass box",
"whale oil",
"aladdin lamp",
"glass oil lamp",
"attack on titan",
"tokyo ghoul",
"joan crawford",
"barbara feldon",
"coin banks vintage",
"wooden bank",
"building bank",
"cgc ss stan lee",
"spiderman 1",
"marvel comics 9.8",
"gerz stein",
"stein",
"german beer mugs",
"tole lamp",
"brass cherub",
"vintage desk",
"predator hunters",
"the walking dead 20",
"walking dead comic #100",
"kankakee",
"galesburg illinois",
"decatur illinois",
"payphone",
"vintage rotary phone",
"rotary wall phone",
"parker duofold",
"parker 51",
"zippo harley",
"camel zippo",
"beer signs budweiser neon",
"budweiser clydesdale",
"skeleton keys",
"padlock",
"breyerfest",
"breyer roan",
"vintage planter",
"cat planter",
"vintage pic",
"toy steam roller",
"plaid wool blanket",
"pendleton blanket",
"disney pewter",
"disney ceramic figurines",
"gumball machine",
"penny machine",
"soda pop sign",
"fence sign",
"match holder porcelain",
"pig match",
"bullet shot glass",
"espresso shot glass",
"vintage metal chest",
"wooden tool box",
"kennedy memorabilia",
"king george queen mary",
"masonic apron",
"trail of painted ponys",
"united delco",
"christmas carolers",
"calif license plates",
"ny license plate",
"military police patches",
"white flower pitcher vase",
"ride poster",
"greek vase",
"absolut vodka bottle",
"holt howard",
"girl scout books",
"angel ornaments",
"piggy piggy banks",
"queen mary",
"goofy phone",
"tupperware bowls",
"sluice",
"x-men 9.8",
"lenox picture frame",
"precious moments figurines",
"victorian photo album",
"woven basket",
"epaulettes",
"waterman rollerball pen",
"magnavox transistor radio",
"tom clark gnomes",
"pinball machine",
"scales of justice",
"see hear speak no evil",
"railroad book",
"disney bank",
"ronald reagan autographed",
"stop sign",
"darth vader 3",
"wolverine 15",
"fire department historical memorabilia",
"tea tags",
"resin easter",
"batman statue",
"michael myers mask",
"large easter eggs",
"m998 hmmwv",
"star trek cards",
"poker table",
"national cash register",
"sewing box",
"empty green bottles",
"herb grinder",
"barber bottle",
"book storage box",
"rooster creamer",
"beer tap handle",
"pyramid of giza",
"pilot helmet",
"old fitzgerald",
"hess truck",
"alpha kappa alpha",
"slide rule",
"medals ribbons us",
"movie refrigerator magnets",
"batman and robin 1",
"vintage sheaffer fountain pen",
"harley-davidson zippo lighter",
"star wars card trader pack art",
"the movie collection goku figure",
"dragon ball statue resin",
"bell key chain keyfob",
"a charlie brown christmas",
"atlantic city casino chips",
"green lantern green arrow comics"]
hits = []
for i in range(len(queries)):

    query = \
    {  
    "size": 1000000,
    "query": { "match": { "Title": queries[i] } }
    }

    res = es.search(index='article_bm25', body=query)

    
    for rank, hit in enumerate(res['hits']['hits'], 1):
        hits.append('{}\tQ{}\t{}\t{}\t{}\t{}'.format(i + 1, 0, hit['_id'], rank, hit['_score'], 'title-test'))

print('\n'.join(hits))
